BoxLayoutExample:

<BoxLayoutExample>:
    orientation: 'vertical'
    Button:
        text: 'Button 1'
    Button:
        text: 'Button 2'
    Label:
        text: 'Label 1'
    Button:
        text: 'Button 3'

<MainWidget>:
    Button:
        text: 'Hello'
        size: '100dp', '100dp'
        pos: '100dp', '200dp'
    Label:
        text: 'Hello 2'
        size: '100dp', '100dp'
        pos: '200dp', '200dp'
        color: 39, 79, 89, 1
